// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package store

import (
	"context"
)

const DeclareJob = `-- name: DeclareJob :exec
INSERT INTO job (name, executor_type, params, timeout, retry_policy)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name) DO UPDATE SET
    executor_type = EXCLUDED.executor_type,
    params        = EXCLUDED.params,
    timeout       = EXCLUDED.timeout,
    retry_policy  = EXCLUDED.retry_policy,
    updated_at    = now()
`

type DeclareJobParams struct {
	Name         string
	ExecutorType string
	Params       []byte
	Timeout      int32
	RetryPolicy  []byte
}

// §2.1 Jobs.Declare: upsert by name
func (q *Queries) DeclareJob(ctx context.Context, db DBTX, arg DeclareJobParams) error {
	_, err := db.Exec(ctx, DeclareJob,
		arg.Name,
		arg.ExecutorType,
		arg.Params,
		arg.Timeout,
		arg.RetryPolicy,
	)
	return err
}

const DeleteJob = `-- name: DeleteJob :execrows
DELETE FROM job WHERE name = $1
`

// §3.3 Jobs.Delete: FK RESTRICT from workflow_node / schedule surfaces as 23503 → ErrReferenced
func (q *Queries) DeleteJob(ctx context.Context, db DBTX, name string) (int64, error) {
	result, err := db.Exec(ctx, DeleteJob, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const JobExists = `-- name: JobExists :one
SELECT EXISTS (SELECT 1 FROM job WHERE name = $1) AS found
`

// §2.1 Jobs.Trigger: zero rows from the INSERT is ErrNotFound when the job is missing, else a dedup conflict
func (q *Queries) JobExists(ctx context.Context, db DBTX, name string) (bool, error) {
	row := db.QueryRow(ctx, JobExists, name)
	var found bool
	err := row.Scan(&found)
	return found, err
}
