// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_run.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const CancelRun = `-- name: CancelRun :one
UPDATE job_run
   SET state            = CASE WHEN state = 'pending' THEN 'cancelled' ELSE state END,
       finished_at      = CASE WHEN state = 'pending' THEN now() ELSE finished_at END,
       cancel_requested = CASE WHEN state = 'running' THEN true ELSE cancel_requested END
 WHERE id = $1 AND state IN ('pending', 'running') AND workflow_run_id IS NULL
   AND (state = 'pending' OR NOT cancel_requested)
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type CancelRunRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.5 Runs.Cancel: plain runs only; a pending row ends now, a running row is flagged and its
// holder settles it as cancelled after the next heartbeat. One statement for both states: a row
// that a concurrent claim or settle moves between them is re-checked on its new version, so
// zero rows means terminal, already requested, a node, or missing; never "moved".
func (q *Queries) CancelRun(ctx context.Context, db DBTX, id int64) (CancelRunRow, error) {
	row := db.QueryRow(ctx, CancelRun, id)
	var i CancelRunRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const ClaimExpired = `-- name: ClaimExpired :many
WITH picked AS (
    SELECT id FROM job_run
     WHERE state = 'running' AND executor_type = ANY($3::text[]) AND lease_expires_at <= now()
     ORDER BY lease_expires_at, id LIMIT $4::int
       FOR UPDATE SKIP LOCKED)
UPDATE job_run r
   SET attempt = LEAST(r.attempt + 1, 32767),
       errors = r.errors || jsonb_build_array(jsonb_build_object(
                  'attempt', LEAST(r.attempt + 1, 32767), 'at', now(), 'kind', 'interrupted',
                  'message', 'lease expired; last owner ' || coalesce(r.extra ->> 'lease_owner', '?'))),
       lease_token = gen_random_uuid(), extra = jsonb_set(r.extra, '{lease_owner}', to_jsonb($1::text)),
       lease_expires_at = now() + $2::interval, started_at = now()
  FROM picked WHERE r.id = picked.id
RETURNING r.id, r.job_name, r.workflow_run_id, r.executor_type, r.params, r.timeout,
          r.retry_policy, r.attempt, r.cancel_requested, r.lease_token::uuid AS lease_token,
          extract(epoch FROM now() - r.run_at)::float8 AS waited_sec, r.extra
`

type ClaimExpiredParams struct {
	Owner         string
	LeaseTtl      time.Duration
	ExecutorTypes []string
	Lim           int32
}

type ClaimExpiredRow struct {
	Id              int64
	JobName         string
	WorkflowRunId   *int64
	ExecutorType    string
	Params          []byte
	Timeout         int32
	RetryPolicy     []byte
	Attempt         int16
	CancelRequested bool
	LeaseToken      uuid.UUID
	WaitedSec       float64
	Extra           []byte
}

// §2.2 branch two: running rows whose lease expired via idx_job_run_running; the previous holder counts as one interrupted attempt.
// attempt is a smallint and max_attempts may be 32767: a holder that crashes at the cap would otherwise overflow the
// next reclaim and fail the whole batch; capped, the post-claim check settles it failed (§2.2).
func (q *Queries) ClaimExpired(ctx context.Context, db DBTX, arg ClaimExpiredParams) ([]ClaimExpiredRow, error) {
	rows, err := db.Query(ctx, ClaimExpired,
		arg.Owner,
		arg.LeaseTtl,
		arg.ExecutorTypes,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimExpiredRow{}
	for rows.Next() {
		var i ClaimExpiredRow
		if err := rows.Scan(
			&i.Id,
			&i.JobName,
			&i.WorkflowRunId,
			&i.ExecutorType,
			&i.Params,
			&i.Timeout,
			&i.RetryPolicy,
			&i.Attempt,
			&i.CancelRequested,
			&i.LeaseToken,
			&i.WaitedSec,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ClaimPending = `-- name: ClaimPending :many
WITH picked AS (
    SELECT id FROM job_run
     WHERE state = 'pending' AND executor_type = ANY($3::text[]) AND run_at <= now()
     ORDER BY run_at LIMIT $4::int
       FOR UPDATE SKIP LOCKED)
UPDATE job_run r
   SET state = 'running', lease_token = gen_random_uuid(),
       extra = jsonb_set(r.extra, '{lease_owner}', to_jsonb($1::text)),
       lease_expires_at = now() + $2::interval, started_at = now()
  FROM picked WHERE r.id = picked.id
RETURNING r.id, r.job_name, r.workflow_run_id, r.executor_type, r.params, r.timeout,
          r.retry_policy, r.attempt, r.cancel_requested, r.lease_token::uuid AS lease_token,
          extract(epoch FROM now() - r.run_at)::float8 AS waited_sec, r.extra
`

type ClaimPendingParams struct {
	Owner         string
	LeaseTtl      time.Duration
	ExecutorTypes []string
	Lim           int32
}

type ClaimPendingRow struct {
	Id              int64
	JobName         string
	WorkflowRunId   *int64
	ExecutorType    string
	Params          []byte
	Timeout         int32
	RetryPolicy     []byte
	Attempt         int16
	CancelRequested bool
	LeaseToken      uuid.UUID
	WaitedSec       float64
	Extra           []byte
}

// §2.2 branch one: due pending rows via idx_job_run_claim
func (q *Queries) ClaimPending(ctx context.Context, db DBTX, arg ClaimPendingParams) ([]ClaimPendingRow, error) {
	rows, err := db.Query(ctx, ClaimPending,
		arg.Owner,
		arg.LeaseTtl,
		arg.ExecutorTypes,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingRow{}
	for rows.Next() {
		var i ClaimPendingRow
		if err := rows.Scan(
			&i.Id,
			&i.JobName,
			&i.WorkflowRunId,
			&i.ExecutorType,
			&i.Params,
			&i.Timeout,
			&i.RetryPolicy,
			&i.Attempt,
			&i.CancelRequested,
			&i.LeaseToken,
			&i.WaitedSec,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindDedupRun = `-- name: FindDedupRun :one
SELECT id FROM job_run
 WHERE job_name = $1 AND dedup_key = $2::text AND schedule_name IS NULL
`

type FindDedupRunParams struct {
	JobName  string
	DedupKey string
}

// §2.1: the run holding a user dedup key, terminal or not (idx_job_run_dedup)
func (q *Queries) FindDedupRun(ctx context.Context, db DBTX, arg FindDedupRunParams) (int64, error) {
	row := db.QueryRow(ctx, FindDedupRun, arg.JobName, arg.DedupKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const FindInflightBeat = `-- name: FindInflightBeat :one
SELECT id FROM job_run
 WHERE job_name = $1 AND dedup_key = $2::text AND schedule_name IS NOT NULL AND state IN ('pending', 'running')
`

type FindInflightBeatParams struct {
	JobName  string
	DedupKey string
}

// §2.1: the in-flight overlap=skip beat holding 'sched:<name>' (idx_job_run_overlap)
func (q *Queries) FindInflightBeat(ctx context.Context, db DBTX, arg FindInflightBeatParams) (int64, error) {
	row := db.QueryRow(ctx, FindInflightBeat, arg.JobName, arg.DedupKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const GetJobRun = `-- name: GetJobRun :one
SELECT id, job_name, schedule_name, scheduled_at, dedup_key, workflow_run_id, executor_type, params, timeout, retry_policy, state, attempt, cancel_requested, run_at, lease_expires_at, lease_token, created_at, started_at, finished_at, output, errors, extra FROM job_run WHERE id = $1
`

// §3.3 Runs.Get and the tests' state reads
func (q *Queries) GetJobRun(ctx context.Context, db DBTX, id int64) (JobRun, error) {
	row := db.QueryRow(ctx, GetJobRun, id)
	var i JobRun
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.ScheduleName,
		&i.ScheduledAt,
		&i.DedupKey,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.Params,
		&i.Timeout,
		&i.RetryPolicy,
		&i.State,
		&i.Attempt,
		&i.CancelRequested,
		&i.RunAt,
		&i.LeaseExpiresAt,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Output,
		&i.Errors,
		&i.Extra,
	)
	return i, err
}

const Heartbeat = `-- name: Heartbeat :many
UPDATE job_run r
   SET lease_expires_at = LEAST(now() + $1::interval,
                                r.started_at + r.timeout * interval '1 second' + $2::interval)
  FROM (SELECT unnest($3::bigint[]) AS id, unnest($4::uuid[]) AS token) v
 WHERE r.id = v.id AND r.lease_token = v.token AND r.state = 'running'
RETURNING r.id, r.cancel_requested,
          coalesce((SELECT w.state = 'cancelling' FROM workflow_run w WHERE w.id = r.workflow_run_id), false)::boolean AS wf_cancelling
`

type HeartbeatParams struct {
	LeaseTtl      time.Duration
	CancelTimeout time.Duration
	Ids           []int64
	Tokens        []uuid.UUID
}

type HeartbeatRow struct {
	Id              int64
	CancelRequested bool
	WfCancelling    bool
}

// §2.3: one statement renews every lease this process holds; only lease_expires_at changes (HOT);
// renewal is capped at started_at + timeout + CancelTimeout; ids missing from the result lost their lease
func (q *Queries) Heartbeat(ctx context.Context, db DBTX, arg HeartbeatParams) ([]HeartbeatRow, error) {
	rows, err := db.Query(ctx, Heartbeat,
		arg.LeaseTtl,
		arg.CancelTimeout,
		arg.Ids,
		arg.Tokens,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartbeatRow{}
	for rows.Next() {
		var i HeartbeatRow
		if err := rows.Scan(&i.Id, &i.CancelRequested, &i.WfCancelling); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListJobRuns = `-- name: ListJobRuns :many
SELECT id, job_name, schedule_name, scheduled_at, dedup_key, workflow_run_id, executor_type, params, timeout, retry_policy, state, attempt, cancel_requested, run_at, lease_expires_at, lease_token, created_at, started_at, finished_at, output, errors, extra FROM job_run
 WHERE ($1::text IS NULL OR job_name = $1::text)
   AND ($2::text IS NULL OR state = $2::text)
   AND ($3::bigint = 0 OR id < $3::bigint)
 ORDER BY id DESC LIMIT $4::int
`

type ListJobRunsParams struct {
	JobName *string
	State   *string
	Cursor  int64
	Lim     int32
}

// §3.3 Runs.List: newest first, cursor = last id of the previous page, via idx_job_run_job
func (q *Queries) ListJobRuns(ctx context.Context, db DBTX, arg ListJobRunsParams) ([]JobRun, error) {
	rows, err := db.Query(ctx, ListJobRuns,
		arg.JobName,
		arg.State,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobRun{}
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.Id,
			&i.JobName,
			&i.ScheduleName,
			&i.ScheduledAt,
			&i.DedupKey,
			&i.WorkflowRunId,
			&i.ExecutorType,
			&i.Params,
			&i.Timeout,
			&i.RetryPolicy,
			&i.State,
			&i.Attempt,
			&i.CancelRequested,
			&i.RunAt,
			&i.LeaseExpiresAt,
			&i.LeaseToken,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Output,
			&i.Errors,
			&i.Extra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LockPlainRunState = `-- name: LockPlainRunState :one
SELECT state FROM job_run WHERE id = $1 AND workflow_run_id IS NULL FOR UPDATE
`

// §2.5 / §2.9: scheduled Resume locks its plain run only after the name and schedule row; nodes are never locked here.
func (q *Queries) LockPlainRunState(ctx context.Context, db DBTX, id int64) (string, error) {
	row := db.QueryRow(ctx, LockPlainRunState, id)
	var state string
	err := row.Scan(&state)
	return state, err
}

const NextPendingAt = `-- name: NextPendingAt :many
SELECT x.run_at::timestamptz AS next_due, clock_timestamp()::timestamptz AS db_now
  FROM unnest($1::text[]) AS t(executor_type)
  CROSS JOIN LATERAL (
    SELECT run_at FROM job_run
     WHERE state = 'pending' AND executor_type = t.executor_type
     ORDER BY run_at LIMIT 1) x
`

type NextPendingAtRow struct {
	NextDue time.Time
	DbNow   time.Time
}

// §2.2 / §2.7: the earliest pending run_at per registered type, one idx_job_run_claim probe each; the caller
// takes the minimum. Due rows are included on purpose: one that came due after the claim statement, or one
// another instance's claim skipped and then rolled back, is found here and reclaimed after wakeFloor instead
// of at the next poll. db_now is clock_timestamp(): now() would be the transaction start
func (q *Queries) NextPendingAt(ctx context.Context, db DBTX, executorTypes []string) ([]NextPendingAtRow, error) {
	rows, err := db.Query(ctx, NextPendingAt, executorTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextPendingAtRow{}
	for rows.Next() {
		var i NextPendingAtRow
		if err := rows.Scan(&i.NextDue, &i.DbNow); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ResumeRun = `-- name: ResumeRun :one
UPDATE job_run
   SET state = 'pending', attempt = 0, run_at = now(),
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner',
       started_at = NULL, finished_at = NULL, output = NULL, cancel_requested = false
 WHERE id = $1 AND workflow_run_id IS NULL AND state IN ('failed', 'cancelled')
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type ResumeRunRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.5: ordinary terminal runs only; recheck state after a concurrent resume.
func (q *Queries) ResumeRun(ctx context.Context, db DBTX, id int64) (ResumeRunRow, error) {
	row := db.QueryRow(ctx, ResumeRun, id)
	var i ResumeRunRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const RunIsNode = `-- name: RunIsNode :one
SELECT (workflow_run_id IS NOT NULL)::boolean AS is_node FROM job_run WHERE id = $1
`

// §2.5 Runs.Cancel: a node is cancelled through its parent (Workflows.CancelRun), never directly
func (q *Queries) RunIsNode(ctx context.Context, db DBTX, id int64) (bool, error) {
	row := db.QueryRow(ctx, RunIsNode, id)
	var is_node bool
	err := row.Scan(&is_node)
	return is_node, err
}

const RunResumeIdentity = `-- name: RunResumeIdentity :one
SELECT schedule_name, workflow_run_id FROM job_run WHERE id = $1
`

type RunResumeIdentityRow struct {
	ScheduleName  *string
	WorkflowRunId *int64
}

// §2.5 / §2.9: read immutable ownership without locks before choosing the scheduled Resume lock order.
func (q *Queries) RunResumeIdentity(ctx context.Context, db DBTX, id int64) (RunResumeIdentityRow, error) {
	row := db.QueryRow(ctx, RunResumeIdentity, id)
	var i RunResumeIdentityRow
	err := row.Scan(&i.ScheduleName, &i.WorkflowRunId)
	return i, err
}

const SettleCancelled = `-- name: SettleCancelled :one
UPDATE job_run
   SET state = 'cancelled', finished_at = now(),
       errors = errors || COALESCE($1::jsonb, '[]'::jsonb),
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner'
 WHERE id = $2 AND lease_token = $3::uuid AND state = 'running'
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type SettleCancelledParams struct {
	Err   []byte
	Id    int64
	Token uuid.UUID
}

type SettleCancelledRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.4 cancelled exit, same fence
func (q *Queries) SettleCancelled(ctx context.Context, db DBTX, arg SettleCancelledParams) (SettleCancelledRow, error) {
	row := db.QueryRow(ctx, SettleCancelled, arg.Err, arg.Id, arg.Token)
	var i SettleCancelledRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const SettleFailed = `-- name: SettleFailed :one
UPDATE job_run
   SET state = CASE WHEN cancel_requested OR $1::boolean THEN 'cancelled' ELSE 'failed' END,
       attempt = attempt + 1, errors = errors || $2::jsonb, finished_at = now(),
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner'
 WHERE id = $3 AND lease_token = $4::uuid AND state = 'running'
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type SettleFailedParams struct {
	WfCancelling bool
	Err          []byte
	Id           int64
	Token        uuid.UUID
}

type SettleFailedRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.4 permanent failure or no attempts left
func (q *Queries) SettleFailed(ctx context.Context, db DBTX, arg SettleFailedParams) (SettleFailedRow, error) {
	row := db.QueryRow(ctx, SettleFailed,
		arg.WfCancelling,
		arg.Err,
		arg.Id,
		arg.Token,
	)
	var i SettleFailedRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const SettleInterrupted = `-- name: SettleInterrupted :one
UPDATE job_run
   SET state = CASE WHEN cancel_requested OR $1::boolean THEN 'cancelled' ELSE 'failed' END,
       finished_at = now(),
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner'
 WHERE id = $2 AND lease_token = $3::uuid AND state = 'running'
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type SettleInterruptedParams struct {
	WfCancelling bool
	Id           int64
	Token        uuid.UUID
}

type SettleInterruptedRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.2: reclaimed with attempt >= max_attempts; the interrupted entry was appended by ClaimExpired
func (q *Queries) SettleInterrupted(ctx context.Context, db DBTX, arg SettleInterruptedParams) (SettleInterruptedRow, error) {
	row := db.QueryRow(ctx, SettleInterrupted, arg.WfCancelling, arg.Id, arg.Token)
	var i SettleInterruptedRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const SettleReleased = `-- name: SettleReleased :one
UPDATE job_run
   SET state       = CASE WHEN cancel_requested OR $1::boolean THEN 'cancelled' ELSE 'pending' END,
       finished_at = CASE WHEN cancel_requested OR $1::boolean THEN now() END,
       run_at = now(), errors = errors || $2::jsonb,
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner'
 WHERE id = $3 AND lease_token = $4::uuid AND state = 'running'
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra,
          (SELECT count(*) FROM jsonb_array_elements(errors) x WHERE x->>'kind' = 'released')::int AS released_count
`

type SettleReleasedParams struct {
	WfCancelling bool
	Err          []byte
	Id           int64
	Token        uuid.UUID
}

type SettleReleasedRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
	ReleasedCount int32
}

// §2.4 / §2.6 graceful shutdown: back to pending now, attempt unchanged, a released entry for the alert
func (q *Queries) SettleReleased(ctx context.Context, db DBTX, arg SettleReleasedParams) (SettleReleasedRow, error) {
	row := db.QueryRow(ctx, SettleReleased,
		arg.WfCancelling,
		arg.Err,
		arg.Id,
		arg.Token,
	)
	var i SettleReleasedRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
		&i.ReleasedCount,
	)
	return i, err
}

const SettleRetry = `-- name: SettleRetry :one
UPDATE job_run
   SET state       = CASE WHEN cancel_requested OR $1::boolean THEN 'cancelled' ELSE 'pending' END,
       finished_at = CASE WHEN cancel_requested OR $1::boolean THEN now() END,
       attempt = attempt + 1, run_at = now() + $2::interval, errors = errors || $3::jsonb,
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner'
 WHERE id = $4 AND lease_token = $5::uuid AND state = 'running'
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type SettleRetryParams struct {
	WfCancelling bool
	Backoff      time.Duration
	Err          []byte
	Id           int64
	Token        uuid.UUID
}

type SettleRetryRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.4 retryable failure with attempts left: pending again after backoff
func (q *Queries) SettleRetry(ctx context.Context, db DBTX, arg SettleRetryParams) (SettleRetryRow, error) {
	row := db.QueryRow(ctx, SettleRetry,
		arg.WfCancelling,
		arg.Backoff,
		arg.Err,
		arg.Id,
		arg.Token,
	)
	var i SettleRetryRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const SettleSnoozed = `-- name: SettleSnoozed :one
UPDATE job_run
   SET state       = CASE WHEN cancel_requested OR $1::boolean THEN 'cancelled' ELSE 'pending' END,
       finished_at = CASE WHEN cancel_requested OR $1::boolean THEN now() END,
       run_at = now() + $2::interval
              + CASE WHEN $3::boolean THEN interval '1 microsecond' ELSE interval '0' END,
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner'
 WHERE id = $4 AND lease_token = $5::uuid AND state = 'running'
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type SettleSnoozedParams struct {
	WfCancelling bool
	Delay        time.Duration
	RoundUp      bool
	Id           int64
	Token        uuid.UUID
}

type SettleSnoozedRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.4 / §3.2: normal waiting, no attempt/error/output change; cancellation still wins.
// Native interval input also handles PG 13; add the rounding remainder without Duration overflow.
// sqlc.arg avoids sqlc 1.31's @ rewrite bug around this interval CASE.
func (q *Queries) SettleSnoozed(ctx context.Context, db DBTX, arg SettleSnoozedParams) (SettleSnoozedRow, error) {
	row := db.QueryRow(ctx, SettleSnoozed,
		arg.WfCancelling,
		arg.Delay,
		arg.RoundUp,
		arg.Id,
		arg.Token,
	)
	var i SettleSnoozedRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const SettleSucceeded = `-- name: SettleSucceeded :one

UPDATE job_run
   SET state = 'succeeded', output = $1, finished_at = now(),
       lease_token = NULL, lease_expires_at = NULL, extra = extra - 'lease_owner'
 WHERE id = $2 AND lease_token = $3::uuid AND state = 'running'
RETURNING id, job_name, workflow_run_id, executor_type, state, lease_token, extra
`

type SettleSucceededParams struct {
	Output []byte
	Id     int64
	Token  uuid.UUID
}

type SettleSucceededRow struct {
	Id            int64
	JobName       string
	WorkflowRunId *int64
	ExecutorType  string
	State         string
	LeaseToken    *uuid.UUID
	Extra         []byte
}

// §2.4 settle: one fenced UPDATE per outcome; WHERE lease_token = @token::uuid AND state = 'running' is the fence,
// ErrNoRows = ErrLeaseLost. Non-terminal outcomes apply the cancel-hit CASE:
// cancel_requested OR @wf_cancelling → cancelled instead of pending / failed.
// §2.4 succeeded exit; the fence is lease_token AND state = 'running', zero rows = ErrLeaseLost
func (q *Queries) SettleSucceeded(ctx context.Context, db DBTX, arg SettleSucceededParams) (SettleSucceededRow, error) {
	row := db.QueryRow(ctx, SettleSucceeded, arg.Output, arg.Id, arg.Token)
	var i SettleSucceededRow
	err := row.Scan(
		&i.Id,
		&i.JobName,
		&i.WorkflowRunId,
		&i.ExecutorType,
		&i.State,
		&i.LeaseToken,
		&i.Extra,
	)
	return i, err
}

const TriggerJob = `-- name: TriggerJob :one
INSERT INTO job_run (job_name, dedup_key, schedule_name, scheduled_at, executor_type, params, timeout, retry_policy, state, run_at, extra)
SELECT j.name, $1::text, $2::text, $3::timestamptz,
       j.executor_type, j.params || $4::jsonb, j.timeout, j.retry_policy,
       'pending', coalesce($5::timestamptz, now()), coalesce($6::jsonb, '{}'::jsonb)
  FROM job j WHERE j.name = $7
ON CONFLICT DO NOTHING
RETURNING id
`

type TriggerJobParams struct {
	DedupKey     *string
	ScheduleName *string
	ScheduledAt  *time.Time
	Params       []byte
	RunAt        *time.Time
	Extra        []byte
	JobName      string
}

// §2.1 Jobs.Trigger: snapshot the job into a pending run; ErrNoRows = job missing or dedup conflict
func (q *Queries) TriggerJob(ctx context.Context, db DBTX, arg TriggerJobParams) (int64, error) {
	row := db.QueryRow(ctx, TriggerJob,
		arg.DedupKey,
		arg.ScheduleName,
		arg.ScheduledAt,
		arg.Params,
		arg.RunAt,
		arg.Extra,
		arg.JobName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
