// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maint.sql

package store

import (
	"context"

	"time"
)

const DeleteOldJobRuns = `-- name: DeleteOldJobRuns :execrows

DELETE FROM job_run r WHERE r.id IN (
    SELECT id FROM job_run
     WHERE state = ANY($1::text[]) AND finished_at < now() - $2::interval AND workflow_run_id IS NULL
     LIMIT $3::int)
   AND r.state = ANY($1::text[]) AND r.finished_at < now() - $2::interval
`

type DeleteOldJobRunsParams struct {
	States []string
	Age    time.Duration
	Lim    int32
}

// The outer WHERE repeats the subquery's conditions on purpose: the subquery picks ids from
// the statement snapshot, and a row locked by a concurrent transaction is re-checked on its
// new version only against the outer WHERE (EvalPlanQual). With id IN (...) alone, a
// workflow_run that Resume just moved back to running would be deleted with all its nodes.
// §6.10 plain runs only: nodes go with their workflow_run (FK cascade), never on their own
func (q *Queries) DeleteOldJobRuns(ctx context.Context, db DBTX, arg DeleteOldJobRunsParams) (int64, error) {
	result, err := db.Exec(ctx, DeleteOldJobRuns, arg.States, arg.Age, arg.Lim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteOldWorkflowRuns = `-- name: DeleteOldWorkflowRuns :execrows
DELETE FROM workflow_run w WHERE w.id IN (
    SELECT id FROM workflow_run
     WHERE state = ANY($1::text[]) AND finished_at < now() - $2::interval
     LIMIT $3::int)
   AND w.state = ANY($1::text[]) AND w.finished_at < now() - $2::interval
`

type DeleteOldWorkflowRunsParams struct {
	States []string
	Age    time.Duration
	Lim    int32
}

// §6.10 retention for workflow runs; nodes go with the parent (ON DELETE CASCADE); outer WHERE re-checked as above
func (q *Queries) DeleteOldWorkflowRuns(ctx context.Context, db DBTX, arg DeleteOldWorkflowRunsParams) (int64, error) {
	result, err := db.Exec(ctx, DeleteOldWorkflowRuns, arg.States, arg.Age, arg.Lim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const MaintenanceUnlock = `-- name: MaintenanceUnlock :exec
SELECT pg_advisory_unlock(hashtext('skein:maint'))
`

// §6.10: released on the same connection; a failed unlock closes that connection instead of pooling it
func (q *Queries) MaintenanceUnlock(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, MaintenanceUnlock)
	return err
}

const StaleJobRuns = `-- name: StaleJobRuns :one
SELECT count(*)::int AS n FROM job_run
 WHERE state IN ('pending', 'running') AND workflow_run_id IS NULL AND created_at < now() - $1::interval
`

// §6.10 stale-active check for plain runs; nodes are counted through their parent
func (q *Queries) StaleJobRuns(ctx context.Context, db DBTX, age time.Duration) (int32, error) {
	row := db.QueryRow(ctx, StaleJobRuns, age)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const StaleWorkflowRuns = `-- name: StaleWorkflowRuns :one
SELECT count(*)::int AS n FROM workflow_run WHERE state IN ('running', 'cancelling') AND created_at < now() - $1::interval
`

// §6.10 stale-active check (stale_active_total): in flight longer than the failed-retention window
func (q *Queries) StaleWorkflowRuns(ctx context.Context, db DBTX, age time.Duration) (int32, error) {
	row := db.QueryRow(ctx, StaleWorkflowRuns, age)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const Stats = `-- name: Stats :one
SELECT count(*) FILTER (WHERE state = 'pending' AND run_at <= now())::int AS pending_due,
       count(*) FILTER (WHERE state = 'running')::int AS running,
       coalesce(extract(epoch FROM now() - min(run_at) FILTER (WHERE state = 'pending' AND run_at <= now())), 0)::float8 AS oldest_pending_sec,
       count(*) FILTER (WHERE state = 'pending' AND run_at <= now() AND NOT (executor_type = ANY($1::text[])))::int AS unregistered_due
  FROM job_run WHERE state IN ('pending', 'running')
`

type StatsRow struct {
	PendingDue       int32
	Running          int32
	OldestPendingSec float64
	UnregisteredDue  int32
}

// §8 Engine.Stats: one statement over the in-flight rows (both partial indexes)
func (q *Queries) Stats(ctx context.Context, db DBTX, registered []string) (StatsRow, error) {
	row := db.QueryRow(ctx, Stats, registered)
	var i StatsRow
	err := row.Scan(
		&i.PendingDue,
		&i.Running,
		&i.OldestPendingSec,
		&i.UnregisteredDue,
	)
	return i, err
}

const TryMaintenanceLock = `-- name: TryMaintenanceLock :one

SELECT pg_try_advisory_lock(hashtext('skein:maint'))::boolean AS locked
`

// §6.10 retention: one holder at a time (session advisory lock), each step its own transaction
// §6.10: session-level advisory lock, one holder per database; the loser reports skipped
func (q *Queries) TryMaintenanceLock(ctx context.Context, db DBTX) (bool, error) {
	row := db.QueryRow(ctx, TryMaintenanceLock)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
