// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"uuid"
)

type Job struct {
	Name         string
	ExecutorType string
	Params       []byte
	Timeout      int32
	RetryPolicy  []byte
	UpdatedAt    time.Time
}

type JobRun struct {
	Id              int64
	JobName         string
	ScheduleName    *string
	ScheduledAt     *time.Time
	DedupKey        *string
	WorkflowRunId   *int64
	ExecutorType    string
	Params          []byte
	Timeout         int32
	RetryPolicy     []byte
	State           string
	Attempt         int16
	CancelRequested bool
	RunAt           time.Time
	LeaseExpiresAt  *time.Time
	LeaseToken      *uuid.UUID
	CreatedAt       time.Time
	StartedAt       *time.Time
	FinishedAt      *time.Time
	Output          []byte
	Errors          []byte
	Extra           []byte
}

type Schedule struct {
	Name         string
	JobName      *string
	WorkflowName *string
	Cron         string
	Timezone     string
	Overlap      string
	Enabled      bool
	NextRunAt    time.Time
	UpdatedAt    time.Time
}

type SchemaVersion struct {
	Version   int32
	AppliedAt time.Time
}

type Workflow struct {
	Name      string
	UpdatedAt time.Time
}

type WorkflowNode struct {
	WorkflowName string
	JobName      string
	Deps         []string
}

type WorkflowRun struct {
	Id           int64
	WorkflowName string
	ScheduleName *string
	ScheduledAt  *time.Time
	DedupKey     *string
	Input        []byte
	Dag          []byte
	State        string
	CreatedAt    time.Time
	FinishedAt   *time.Time
	Extra        []byte
}
