// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_version.sql

package store

import (
	"context"
)

const CurrentSchemaVersion = `-- name: CurrentSchemaVersion :one
SELECT coalesce(max(version), 0)::int AS version FROM schema_version
`

// §2.6: Start refuses to run unless this equals skein.schemaVersion
func (q *Queries) CurrentSchemaVersion(ctx context.Context, db DBTX) (int32, error) {
	row := db.QueryRow(ctx, CurrentSchemaVersion)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const RecordSchemaVersion = `-- name: RecordSchemaVersion :exec
INSERT INTO schema_version (version) VALUES ($1)
`

// §1.3 Migrate: one row per applied migration, under pg_advisory_xact_lock
func (q *Queries) RecordSchemaVersion(ctx context.Context, db DBTX, version int32) error {
	_, err := db.Exec(ctx, RecordSchemaVersion, version)
	return err
}
