// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package store

import (
	"context"
	"time"
)

const AdvanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedule SET next_run_at = $1 WHERE name = $2
`

type AdvanceScheduleParams struct {
	NextRunAt time.Time
	Name      string
}

// §2.1: move the rule to its next fire time; does not touch updated_at and does not notify (§2.7)
func (q *Queries) AdvanceSchedule(ctx context.Context, db DBTX, arg AdvanceScheduleParams) error {
	_, err := db.Exec(ctx, AdvanceSchedule, arg.NextRunAt, arg.Name)
	return err
}

const DbNow = `-- name: DbNow :one
SELECT now()::timestamptz AS now
`

// §2.1 Schedules.Put computes next_run_at from the database clock
func (q *Queries) DbNow(ctx context.Context, db DBTX) (time.Time, error) {
	row := db.QueryRow(ctx, DbNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const DeleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedule WHERE name = $1
`

// §3.3 Schedules.Delete; zero rows = ErrNotFound; the schedule trigger notifies the scanners (§2.7)
func (q *Queries) DeleteSchedule(ctx context.Context, db DBTX, name string) (int64, error) {
	result, err := db.Exec(ctx, DeleteSchedule, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DisableSchedule = `-- name: DisableSchedule :exec
UPDATE schedule SET enabled = false, updated_at = now() WHERE name = $1
`

// §2.1: the rule has no fire time within robfig's five-year horizon; a zero next_run_at would be due every tick
func (q *Queries) DisableSchedule(ctx context.Context, db DBTX, name string) error {
	_, err := db.Exec(ctx, DisableSchedule, name)
	return err
}

const DueScheduleCandidates = `-- name: DueScheduleCandidates :many
SELECT name, next_run_at FROM schedule
 WHERE enabled AND next_run_at <= now()
   AND ($1::timestamptz IS NULL
        OR (next_run_at, name) > ($1::timestamptz, $2::text))
 ORDER BY next_run_at, name LIMIT $3::int
`

type DueScheduleCandidatesParams struct {
	AfterDue  *time.Time
	AfterName string
	Lim       int32
}

type DueScheduleCandidatesRow struct {
	Name      string
	NextRunAt time.Time
}

// §2.1: enumerate without locks, continuing past names held by other transactions until a real batch is filled.
func (q *Queries) DueScheduleCandidates(ctx context.Context, db DBTX, arg DueScheduleCandidatesParams) ([]DueScheduleCandidatesRow, error) {
	rows, err := db.Query(ctx, DueScheduleCandidates, arg.AfterDue, arg.AfterName, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueScheduleCandidatesRow{}
	for rows.Next() {
		var i DueScheduleCandidatesRow
		if err := rows.Scan(&i.Name, &i.NextRunAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSchedule = `-- name: GetSchedule :one
SELECT name, job_name, workflow_name, cron, timezone, overlap, enabled, next_run_at, updated_at FROM schedule WHERE name = $1
`

// §3.3: read back one rule (tests and diagnostics)
func (q *Queries) GetSchedule(ctx context.Context, db DBTX, name string) (Schedule, error) {
	row := db.QueryRow(ctx, GetSchedule, name)
	var i Schedule
	err := row.Scan(
		&i.Name,
		&i.JobName,
		&i.WorkflowName,
		&i.Cron,
		&i.Timezone,
		&i.Overlap,
		&i.Enabled,
		&i.NextRunAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InflightScheduleRunExists = `-- name: InflightScheduleRunExists :one
SELECT (EXISTS (
    SELECT 1 FROM job_run
     WHERE schedule_name = $1::text AND state IN ('pending', 'running') AND id <> $2::bigint
) OR EXISTS (
    SELECT 1 FROM workflow_run
     WHERE schedule_name = $1::text AND state IN ('running', 'cancelling') AND id <> $3::bigint
))::boolean AS found
`

type InflightScheduleRunExistsParams struct {
	Name                 string
	ExcludeRunID         int64
	ExcludeWorkflowRunID int64
}

// §2.1 / §2.5: current skip rules cover historical allow beats and target changes across both run tables.
// The name lock serializes all openings, so these candidates must remain unlocked; settlement may only remove them.
func (q *Queries) InflightScheduleRunExists(ctx context.Context, db DBTX, arg InflightScheduleRunExistsParams) (bool, error) {
	row := db.QueryRow(ctx, InflightScheduleRunExists, arg.Name, arg.ExcludeRunID, arg.ExcludeWorkflowRunID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const LockDueSchedule = `-- name: LockDueSchedule :one
SELECT name, job_name, workflow_name, cron, timezone, overlap, next_run_at, now()::timestamptz AS db_now
  FROM schedule
 WHERE name = $1 AND enabled AND next_run_at <= now()
   FOR UPDATE SKIP LOCKED
`

type LockDueScheduleRow struct {
	Name         string
	JobName      *string
	WorkflowName *string
	Cron         string
	Timezone     string
	Overlap      string
	NextRunAt    time.Time
	DbNow        time.Time
}

// §2.1 / §2.9: only after the name lock; recheck a candidate's current rule and due time without waiting on a row.
func (q *Queries) LockDueSchedule(ctx context.Context, db DBTX, name string) (LockDueScheduleRow, error) {
	row := db.QueryRow(ctx, LockDueSchedule, name)
	var i LockDueScheduleRow
	err := row.Scan(
		&i.Name,
		&i.JobName,
		&i.WorkflowName,
		&i.Cron,
		&i.Timezone,
		&i.Overlap,
		&i.NextRunAt,
		&i.DbNow,
	)
	return i, err
}

const LockScheduleName = `-- name: LockScheduleName :exec
SELECT pg_advisory_xact_lock(hashtext('skein:schedule'), hashtext(jsonb_build_array(current_schema(), $1::text)::text))
`

// §1.3 / §2.1 / §2.5 / §2.9: coordinate a schema/name even while its schedule row is absent.
// The two-integer lock space is separate from the one-bigint maintenance and migration locks.
func (q *Queries) LockScheduleName(ctx context.Context, db DBTX, name string) error {
	_, err := db.Exec(ctx, LockScheduleName, name)
	return err
}

const LockScheduleRule = `-- name: LockScheduleRule :one
SELECT overlap FROM schedule WHERE name = $1 FOR UPDATE
`

// §2.5 / §2.9: scheduled Resume holds the name lock before reading the current rule; no row means deleted.
func (q *Queries) LockScheduleRule(ctx context.Context, db DBTX, name string) (string, error) {
	row := db.QueryRow(ctx, LockScheduleRule, name)
	var overlap string
	err := row.Scan(&overlap)
	return overlap, err
}

const NextScheduleAt = `-- name: NextScheduleAt :one
SELECT next_run_at AS next_due, clock_timestamp()::timestamptz AS db_now FROM schedule WHERE enabled ORDER BY next_run_at LIMIT 1
`

type NextScheduleAtRow struct {
	NextDue time.Time
	DbNow   time.Time
}

// §2.1 / §2.7: the nearest fire time after this tick's advances, read in the same transaction; idx_schedule_due first entry.
// ErrNoRows = no enabled schedule. db_now is clock_timestamp(): now() is the transaction start, and the tick's own
// work (up to 50 fires) would otherwise be waited for a second time
func (q *Queries) NextScheduleAt(ctx context.Context, db DBTX) (NextScheduleAtRow, error) {
	row := db.QueryRow(ctx, NextScheduleAt)
	var i NextScheduleAtRow
	err := row.Scan(&i.NextDue, &i.DbNow)
	return i, err
}

const PutSchedule = `-- name: PutSchedule :exec
INSERT INTO schedule (name, job_name, workflow_name, cron, timezone, overlap, enabled, next_run_at)
VALUES ($1, $2::text, $3::text, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE SET
    job_name = EXCLUDED.job_name, workflow_name = EXCLUDED.workflow_name,
    cron = EXCLUDED.cron, timezone = EXCLUDED.timezone, overlap = EXCLUDED.overlap,
    enabled = EXCLUDED.enabled, updated_at = now(),
    next_run_at = CASE WHEN schedule.cron IS DISTINCT FROM EXCLUDED.cron
                         OR schedule.timezone IS DISTINCT FROM EXCLUDED.timezone
                         OR (NOT schedule.enabled AND EXCLUDED.enabled)
                       THEN EXCLUDED.next_run_at ELSE schedule.next_run_at END
`

type PutScheduleParams struct {
	Name         string
	JobName      *string
	WorkflowName *string
	Cron         string
	Timezone     string
	Overlap      string
	Enabled      bool
	NextRunAt    time.Time
}

// §2.1 Schedules.Put: upsert; next_run_at is recomputed only when the rule changed or the
// schedule went from disabled to enabled, so a rolling deploy does not keep postponing it
func (q *Queries) PutSchedule(ctx context.Context, db DBTX, arg PutScheduleParams) error {
	_, err := db.Exec(ctx, PutSchedule,
		arg.Name,
		arg.JobName,
		arg.WorkflowName,
		arg.Cron,
		arg.Timezone,
		arg.Overlap,
		arg.Enabled,
		arg.NextRunAt,
	)
	return err
}

const TryLockScheduleName = `-- name: TryLockScheduleName :one
SELECT pg_try_advisory_xact_lock(hashtext('skein:schedule'), hashtext(jsonb_build_array(current_schema(), $1::text)::text))::boolean AS locked
`

// §2.1 / §2.9: a scanner never waits while acquiring another name in its batch.
func (q *Queries) TryLockScheduleName(ctx context.Context, db DBTX, name string) (bool, error) {
	row := db.QueryRow(ctx, TryLockScheduleName, name)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
