// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package store

import (
	"context"
	"time"
)

const AdvanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedule SET next_run_at = $1 WHERE name = $2
`

type AdvanceScheduleParams struct {
	NextRunAt time.Time
	Name      string
}

// §6.2: move the rule to its next fire time; does not touch updated_at and does not notify (§6.11)
func (q *Queries) AdvanceSchedule(ctx context.Context, db DBTX, arg AdvanceScheduleParams) error {
	_, err := db.Exec(ctx, AdvanceSchedule, arg.NextRunAt, arg.Name)
	return err
}

const DbNow = `-- name: DbNow :one
SELECT now()::timestamptz AS now
`

// §6.2 Schedules.Put computes next_run_at from the database clock
func (q *Queries) DbNow(ctx context.Context, db DBTX) (time.Time, error) {
	row := db.QueryRow(ctx, DbNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const DeleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedule WHERE name = $1
`

// §8 Schedules.Delete; zero rows = ErrNotFound; the schedule trigger notifies the scanners (§6.11)
func (q *Queries) DeleteSchedule(ctx context.Context, db DBTX, name string) (int64, error) {
	result, err := db.Exec(ctx, DeleteSchedule, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DisableSchedule = `-- name: DisableSchedule :exec
UPDATE schedule SET enabled = false, updated_at = now() WHERE name = $1
`

// §6.2: the rule has no fire time within robfig's five-year horizon; a zero next_run_at would be due every tick
func (q *Queries) DisableSchedule(ctx context.Context, db DBTX, name string) error {
	_, err := db.Exec(ctx, DisableSchedule, name)
	return err
}

const DueSchedules = `-- name: DueSchedules :many
SELECT name, job_name, workflow_name, cron, timezone, overlap, next_run_at, now()::timestamptz AS db_now
  FROM schedule
 WHERE enabled AND next_run_at <= now()
 ORDER BY next_run_at LIMIT $1::int
   FOR UPDATE SKIP LOCKED
`

type DueSchedulesRow struct {
	Name         string
	JobName      *string
	WorkflowName *string
	Cron         string
	Timezone     string
	Overlap      string
	NextRunAt    time.Time
	DbNow        time.Time
}

// §6.2: due schedules, locked so two instances never fire the same one; db_now drives the next computation
func (q *Queries) DueSchedules(ctx context.Context, db DBTX, lim int32) ([]DueSchedulesRow, error) {
	rows, err := db.Query(ctx, DueSchedules, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueSchedulesRow{}
	for rows.Next() {
		var i DueSchedulesRow
		if err := rows.Scan(
			&i.Name,
			&i.JobName,
			&i.WorkflowName,
			&i.Cron,
			&i.Timezone,
			&i.Overlap,
			&i.NextRunAt,
			&i.DbNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSchedule = `-- name: GetSchedule :one
SELECT name, job_name, workflow_name, cron, timezone, overlap, enabled, next_run_at, updated_at FROM schedule WHERE name = $1
`

// §8: read back one rule (tests and diagnostics)
func (q *Queries) GetSchedule(ctx context.Context, db DBTX, name string) (Schedule, error) {
	row := db.QueryRow(ctx, GetSchedule, name)
	var i Schedule
	err := row.Scan(
		&i.Name,
		&i.JobName,
		&i.WorkflowName,
		&i.Cron,
		&i.Timezone,
		&i.Overlap,
		&i.Enabled,
		&i.NextRunAt,
		&i.UpdatedAt,
	)
	return i, err
}

const NextScheduleAt = `-- name: NextScheduleAt :one
SELECT next_run_at AS next_due, clock_timestamp()::timestamptz AS db_now FROM schedule WHERE enabled ORDER BY next_run_at LIMIT 1
`

type NextScheduleAtRow struct {
	NextDue time.Time
	DbNow   time.Time
}

// §6.2 / §6.11: the nearest fire time after this tick's advances, read in the same transaction; idx_schedule_due first entry.
// ErrNoRows = no enabled schedule. db_now is clock_timestamp(): now() is the transaction start, and the tick's own
// work (up to 50 fires) would otherwise be waited for a second time
func (q *Queries) NextScheduleAt(ctx context.Context, db DBTX) (NextScheduleAtRow, error) {
	row := db.QueryRow(ctx, NextScheduleAt)
	var i NextScheduleAtRow
	err := row.Scan(&i.NextDue, &i.DbNow)
	return i, err
}

const PutSchedule = `-- name: PutSchedule :exec
INSERT INTO schedule (name, job_name, workflow_name, cron, timezone, overlap, enabled, next_run_at)
VALUES ($1, $2::text, $3::text, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE SET
    job_name = EXCLUDED.job_name, workflow_name = EXCLUDED.workflow_name,
    cron = EXCLUDED.cron, timezone = EXCLUDED.timezone, overlap = EXCLUDED.overlap,
    enabled = EXCLUDED.enabled, updated_at = now(),
    next_run_at = CASE WHEN schedule.cron IS DISTINCT FROM EXCLUDED.cron
                         OR schedule.timezone IS DISTINCT FROM EXCLUDED.timezone
                         OR (NOT schedule.enabled AND EXCLUDED.enabled)
                       THEN EXCLUDED.next_run_at ELSE schedule.next_run_at END
`

type PutScheduleParams struct {
	Name         string
	JobName      *string
	WorkflowName *string
	Cron         string
	Timezone     string
	Overlap      string
	Enabled      bool
	NextRunAt    time.Time
}

// §6.2 Schedules.Put: upsert; next_run_at is recomputed only when the rule changed or the
// schedule went from disabled to enabled, so a rolling deploy does not keep postponing it
func (q *Queries) PutSchedule(ctx context.Context, db DBTX, arg PutScheduleParams) error {
	_, err := db.Exec(ctx, PutSchedule,
		arg.Name,
		arg.JobName,
		arg.WorkflowName,
		arg.Cron,
		arg.Timezone,
		arg.Overlap,
		arg.Enabled,
		arg.NextRunAt,
	)
	return err
}
