// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package store

import (
	"context"
)

const CurrentSearchPath = `-- name: CurrentSearchPath :one
SELECT current_setting('search_path')::text AS path
`

// §1.3 TriggerTx restores the caller's search_path with this
func (q *Queries) CurrentSearchPath(ctx context.Context, db DBTX) (string, error) {
	row := db.QueryRow(ctx, CurrentSearchPath)
	var path string
	err := row.Scan(&path)
	return path, err
}

const MigrateLock = `-- name: MigrateLock :exec
SELECT pg_advisory_xact_lock(hashtext('skein:migrate'))
`

// §1.3: migrations run serially
func (q *Queries) MigrateLock(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, MigrateLock)
	return err
}

const SchemaVersionTableExists = `-- name: SchemaVersionTableExists :one
SELECT (to_regclass($1::text) IS NOT NULL)::boolean AS found
`

// §1.3 Migrate bootstrap: before the first migration there is no schema_version table
func (q *Queries) SchemaVersionTableExists(ctx context.Context, db DBTX, qualifiedName string) (bool, error) {
	row := db.QueryRow(ctx, SchemaVersionTableExists, qualifiedName)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const SetSearchPath = `-- name: SetSearchPath :exec
SELECT set_config('search_path', $1::text, true)
`

// §1.3 Store.tx: transaction-local search_path (set_config(..., true) == SET LOCAL), nothing leaks to the host's pool;
// the value is <schema>, pg_temp so a session's temp table cannot shadow a library table
func (q *Queries) SetSearchPath(ctx context.Context, db DBTX, path string) error {
	_, err := db.Exec(ctx, SetSearchPath, path)
	return err
}
