// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package store

import (
	"context"
)

const DeclareWorkflow = `-- name: DeclareWorkflow :exec
INSERT INTO workflow (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET updated_at = now()
`

// §2.1 Workflows.Declare: upsert the workflow row; nodes are replaced by the caller in the same transaction
func (q *Queries) DeclareWorkflow(ctx context.Context, db DBTX, name string) error {
	_, err := db.Exec(ctx, DeclareWorkflow, name)
	return err
}

const DeleteWorkflow = `-- name: DeleteWorkflow :execrows
DELETE FROM workflow WHERE name = $1
`

// §3.3 Workflows.Delete: FK RESTRICT from schedule surfaces as 23503 → ErrReferenced; nodes cascade
func (q *Queries) DeleteWorkflow(ctx context.Context, db DBTX, name string) (int64, error) {
	result, err := db.Exec(ctx, DeleteWorkflow, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteWorkflowNodes = `-- name: DeleteWorkflowNodes :exec
DELETE FROM workflow_node WHERE workflow_name = $1
`

// §2.1 Workflows.Declare: the node set is replaced, old rows first
func (q *Queries) DeleteWorkflowNodes(ctx context.Context, db DBTX, workflowName string) error {
	_, err := db.Exec(ctx, DeleteWorkflowNodes, workflowName)
	return err
}

const ExistingJobs = `-- name: ExistingJobs :many
SELECT name FROM job WHERE name = ANY($1::text[])
`

// §2.1 Workflows.Declare validation: every node's job must be declared
func (q *Queries) ExistingJobs(ctx context.Context, db DBTX, names []string) ([]string, error) {
	rows, err := db.Query(ctx, ExistingJobs, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertWorkflowNode = `-- name: InsertWorkflowNode :exec
INSERT INTO workflow_node (workflow_name, job_name, deps) VALUES ($1, $2, $3::text[])
`

type InsertWorkflowNodeParams struct {
	WorkflowName string
	JobName      string
	Deps         []string
}

// §2.1 Workflows.Declare: one row per node after the in-memory validation
func (q *Queries) InsertWorkflowNode(ctx context.Context, db DBTX, arg InsertWorkflowNodeParams) error {
	_, err := db.Exec(ctx, InsertWorkflowNode, arg.WorkflowName, arg.JobName, arg.Deps)
	return err
}

const WorkflowNodes = `-- name: WorkflowNodes :many
SELECT n.job_name, n.deps, j.executor_type, j.params, j.timeout, j.retry_policy
  FROM workflow_node n JOIN job j ON j.name = n.job_name
 WHERE n.workflow_name = $1
 ORDER BY n.job_name
`

type WorkflowNodesRow struct {
	JobName      string
	Deps         []string
	ExecutorType string
	Params       []byte
	Timeout      int32
	RetryPolicy  []byte
}

// §2.1: the only read of definition tables in a workflow's life
func (q *Queries) WorkflowNodes(ctx context.Context, db DBTX, workflowName string) ([]WorkflowNodesRow, error) {
	rows, err := db.Query(ctx, WorkflowNodes, workflowName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowNodesRow{}
	for rows.Next() {
		var i WorkflowNodesRow
		if err := rows.Scan(
			&i.JobName,
			&i.Deps,
			&i.ExecutorType,
			&i.Params,
			&i.Timeout,
			&i.RetryPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
