// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_run.sql

package store

import (
	"context"
	"time"
)

const ActivateNodes = `-- name: ActivateNodes :execrows
UPDATE job_run SET state = 'pending', run_at = now()
 WHERE workflow_run_id = $1::bigint AND job_name = ANY($2::text[]) AND state = 'blocked'
`

type ActivateNodesParams struct {
	WorkflowRunId int64
	JobNames      []string
}

// §2.4 propagate: blocked nodes whose predecessors all succeeded
func (q *Queries) ActivateNodes(ctx context.Context, db DBTX, arg ActivateNodesParams) (int64, error) {
	result, err := db.Exec(ctx, ActivateNodes, arg.WorkflowRunId, arg.JobNames)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const CancelUnstartedNodes = `-- name: CancelUnstartedNodes :execrows
WITH picked AS (
    SELECT id FROM job_run
     WHERE workflow_run_id = $2::bigint AND state IN ('blocked', 'pending')
       FOR UPDATE SKIP LOCKED)
UPDATE job_run r SET state = 'cancelled', finished_at = now(), errors = r.errors || $1::jsonb
  FROM picked WHERE r.id = picked.id AND r.state IN ('blocked', 'pending')
`

type CancelUnstartedNodesParams struct {
	Err           []byte
	WorkflowRunId int64
}

// §2.4 / §2.5 / §2.9: never wait for a claim or heartbeat on a newly running version;
// skipped pending nodes observe the cancelling parent after this or a later claim
func (q *Queries) CancelUnstartedNodes(ctx context.Context, db DBTX, arg CancelUnstartedNodesParams) (int64, error) {
	result, err := db.Exec(ctx, CancelUnstartedNodes, arg.Err, arg.WorkflowRunId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const FinalizeWorkflowRun = `-- name: FinalizeWorkflowRun :exec
UPDATE workflow_run SET state = $1, finished_at = now() WHERE id = $2
`

type FinalizeWorkflowRunParams struct {
	State string
	Id    int64
}

// §2.4 finalize: every node terminal, the run takes succeeded / failed / cancelled
func (q *Queries) FinalizeWorkflowRun(ctx context.Context, db DBTX, arg FinalizeWorkflowRunParams) error {
	_, err := db.Exec(ctx, FinalizeWorkflowRun, arg.State, arg.Id)
	return err
}

const FindDedupWorkflowRun = `-- name: FindDedupWorkflowRun :one
SELECT id FROM workflow_run
 WHERE workflow_name = $1 AND dedup_key = $2::text AND schedule_name IS NULL
`

type FindDedupWorkflowRunParams struct {
	WorkflowName string
	DedupKey     string
}

// §2.1: the workflow run holding a user dedup key, terminal or not (idx_workflow_run_dedup)
func (q *Queries) FindDedupWorkflowRun(ctx context.Context, db DBTX, arg FindDedupWorkflowRunParams) (int64, error) {
	row := db.QueryRow(ctx, FindDedupWorkflowRun, arg.WorkflowName, arg.DedupKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const FindInflightWorkflowBeat = `-- name: FindInflightWorkflowBeat :one
SELECT id FROM workflow_run
 WHERE workflow_name = $1 AND dedup_key = $2::text AND schedule_name IS NOT NULL AND state IN ('running', 'cancelling')
`

type FindInflightWorkflowBeatParams struct {
	WorkflowName string
	DedupKey     string
}

// §2.1: the in-flight overlap=skip beat holding 'sched:<name>' (idx_workflow_run_overlap)
func (q *Queries) FindInflightWorkflowBeat(ctx context.Context, db DBTX, arg FindInflightWorkflowBeatParams) (int64, error) {
	row := db.QueryRow(ctx, FindInflightWorkflowBeat, arg.WorkflowName, arg.DedupKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const GetWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_name, schedule_name, scheduled_at, dedup_key, input, dag, state, created_at, finished_at FROM workflow_run WHERE id = $1
`

// §2.5 Resume and §3.3: the parent row alone
func (q *Queries) GetWorkflowRun(ctx context.Context, db DBTX, id int64) (WorkflowRun, error) {
	row := db.QueryRow(ctx, GetWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.Id,
		&i.WorkflowName,
		&i.ScheduleName,
		&i.ScheduledAt,
		&i.DedupKey,
		&i.Input,
		&i.Dag,
		&i.State,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const InsertNodeRun = `-- name: InsertNodeRun :exec
INSERT INTO job_run (job_name, workflow_run_id, executor_type, params, timeout, retry_policy, state)
VALUES ($1, $2::bigint, $3, $4, $5, $6, $7)
`

type InsertNodeRunParams struct {
	JobName       string
	WorkflowRunId int64
	ExecutorType  string
	Params        []byte
	Timeout       int32
	RetryPolicy   []byte
	State         string
}

// §2.1: one job_run per node, blocked while it has predecessors
func (q *Queries) InsertNodeRun(ctx context.Context, db DBTX, arg InsertNodeRunParams) error {
	_, err := db.Exec(ctx, InsertNodeRun,
		arg.JobName,
		arg.WorkflowRunId,
		arg.ExecutorType,
		arg.Params,
		arg.Timeout,
		arg.RetryPolicy,
		arg.State,
	)
	return err
}

const ListWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_name, schedule_name, scheduled_at, dedup_key, input, dag, state, created_at, finished_at FROM workflow_run
 WHERE ($1::text IS NULL OR workflow_name = $1::text)
   AND ($2::text IS NULL OR state = $2::text)
   AND ($3::bigint = 0 OR id < $3::bigint)
 ORDER BY id DESC LIMIT $4::int
`

type ListWorkflowRunsParams struct {
	WorkflowName *string
	State        *string
	Cursor       int64
	Lim          int32
}

// §3.3 Workflows.ListRuns: newest first, cursor = last id of the previous page, via idx_workflow_run_wf
func (q *Queries) ListWorkflowRuns(ctx context.Context, db DBTX, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := db.Query(ctx, ListWorkflowRuns,
		arg.WorkflowName,
		arg.State,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.Id,
			&i.WorkflowName,
			&i.ScheduleName,
			&i.ScheduledAt,
			&i.DedupKey,
			&i.Input,
			&i.Dag,
			&i.State,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LockWorkflowRun = `-- name: LockWorkflowRun :one
SELECT state, dag FROM workflow_run WHERE id = $1 FOR UPDATE
`

type LockWorkflowRunRow struct {
	State string
	Dag   []byte
}

// §2.4 / §2.5: first link of the lock order workflow_run → job_run
func (q *Queries) LockWorkflowRun(ctx context.Context, db DBTX, id int64) (LockWorkflowRunRow, error) {
	row := db.QueryRow(ctx, LockWorkflowRun, id)
	var i LockWorkflowRunRow
	err := row.Scan(&i.State, &i.Dag)
	return i, err
}

const MarkWorkflowCancelling = `-- name: MarkWorkflowCancelling :execrows
UPDATE workflow_run SET state = 'cancelling' WHERE id = $1 AND state = 'running'
`

// §2.4 / §2.5: fail-fast and Workflows.Cancel: running → cancelling; 0 rows = already cancelling or terminal
func (q *Queries) MarkWorkflowCancelling(ctx context.Context, db DBTX, id int64) (int64, error) {
	result, err := db.Exec(ctx, MarkWorkflowCancelling, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const NodeOutputs = `-- name: NodeOutputs :many
SELECT job_name, output FROM job_run
 WHERE workflow_run_id = $1::bigint AND job_name = ANY($2::text[])
`

type NodeOutputsParams struct {
	WorkflowRunId int64
	JobNames      []string
}

type NodeOutputsRow struct {
	JobName string
	Output  []byte
}

// §2.2 post-claim: the direct predecessors' outputs for Request.Deps
func (q *Queries) NodeOutputs(ctx context.Context, db DBTX, arg NodeOutputsParams) ([]NodeOutputsRow, error) {
	rows, err := db.Query(ctx, NodeOutputs, arg.WorkflowRunId, arg.JobNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeOutputsRow{}
	for rows.Next() {
		var i NodeOutputsRow
		if err := rows.Scan(&i.JobName, &i.Output); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const NodeStates = `-- name: NodeStates :many
SELECT job_name, state FROM job_run WHERE workflow_run_id = $1::bigint
`

type NodeStatesRow struct {
	JobName string
	State   string
}

// §2.4 / §2.5: propagate / finalize / resume view of the workflow, via idx_job_run_node
func (q *Queries) NodeStates(ctx context.Context, db DBTX, workflowRunID int64) ([]NodeStatesRow, error) {
	rows, err := db.Query(ctx, NodeStates, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeStatesRow{}
	for rows.Next() {
		var i NodeStatesRow
		if err := rows.Scan(&i.JobName, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ReopenWorkflowRun = `-- name: ReopenWorkflowRun :exec
UPDATE workflow_run SET state = 'running', finished_at = NULL WHERE id = $1
`

// §2.5: back to running; the dedup index may reject it with 23505 → ErrDuplicate
func (q *Queries) ReopenWorkflowRun(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, ReopenWorkflowRun, id)
	return err
}

const ResumeNodes = `-- name: ResumeNodes :exec
UPDATE job_run r
   SET state = v.state, attempt = 0, run_at = now(),
       started_at = NULL, finished_at = NULL, output = NULL
  FROM (SELECT unnest($2::text[]) AS job_name, unnest($3::text[]) AS state) v
 WHERE r.workflow_run_id = $1::bigint AND r.job_name = v.job_name
`

type ResumeNodesParams struct {
	WorkflowRunId int64
	JobNames      []string
	States        []string
}

// §2.5: the reset set goes back to pending / blocked with attempt 0; errors are kept
func (q *Queries) ResumeNodes(ctx context.Context, db DBTX, arg ResumeNodesParams) error {
	_, err := db.Exec(ctx, ResumeNodes, arg.WorkflowRunId, arg.JobNames, arg.States)
	return err
}

const TriggerWorkflow = `-- name: TriggerWorkflow :one
INSERT INTO workflow_run (workflow_name, dedup_key, schedule_name, scheduled_at, input, dag, state)
VALUES ($1, $2::text, $3::text, $4::timestamptz,
        $5::jsonb, $6::jsonb, 'running')
ON CONFLICT DO NOTHING
RETURNING id
`

type TriggerWorkflowParams struct {
	WorkflowName string
	DedupKey     *string
	ScheduleName *string
	ScheduledAt  *time.Time
	Input        []byte
	Dag          []byte
}

// §2.1: the parent row with the DAG snapshot; ErrNoRows = dedup conflict
func (q *Queries) TriggerWorkflow(ctx context.Context, db DBTX, arg TriggerWorkflowParams) (int64, error) {
	row := db.QueryRow(ctx, TriggerWorkflow,
		arg.WorkflowName,
		arg.DedupKey,
		arg.ScheduleName,
		arg.ScheduledAt,
		arg.Input,
		arg.Dag,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const WorkflowRunHeader = `-- name: WorkflowRunHeader :one
SELECT state, input, dag FROM workflow_run WHERE id = $1
`

type WorkflowRunHeaderRow struct {
	State string
	Input []byte
	Dag   []byte
}

// §2.2: the worker reads the parent without a lock
func (q *Queries) WorkflowRunHeader(ctx context.Context, db DBTX, id int64) (WorkflowRunHeaderRow, error) {
	row := db.QueryRow(ctx, WorkflowRunHeader, id)
	var i WorkflowRunHeaderRow
	err := row.Scan(&i.State, &i.Input, &i.Dag)
	return i, err
}

const WorkflowRunWithNodes = `-- name: WorkflowRunWithNodes :many
SELECT w.id, w.workflow_name, w.schedule_name, w.scheduled_at, w.dedup_key, w.input, w.dag, w.state, w.created_at, w.finished_at, r.id, r.job_name, r.schedule_name, r.scheduled_at, r.dedup_key, r.workflow_run_id, r.executor_type, r.params, r.timeout, r.retry_policy, r.state, r.attempt, r.cancel_requested, r.run_at, r.lease_expires_at, r.lease_token, r.lease_owner, r.created_at, r.started_at, r.finished_at, r.output, r.errors
  FROM workflow_run w JOIN job_run r ON r.workflow_run_id = w.id
 WHERE w.id = $1 ORDER BY r.job_name
`

type WorkflowRunWithNodesRow struct {
	WorkflowRun WorkflowRun
	JobRun      JobRun
}

// §3.3 Workflows.GetRun: parent and nodes from one statement snapshot, so a concurrent Resume
// cannot show a failed parent next to pending nodes; a run always has at least one node
func (q *Queries) WorkflowRunWithNodes(ctx context.Context, db DBTX, id int64) ([]WorkflowRunWithNodesRow, error) {
	rows, err := db.Query(ctx, WorkflowRunWithNodes, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRunWithNodesRow{}
	for rows.Next() {
		var i WorkflowRunWithNodesRow
		if err := rows.Scan(
			&i.WorkflowRun.Id,
			&i.WorkflowRun.WorkflowName,
			&i.WorkflowRun.ScheduleName,
			&i.WorkflowRun.ScheduledAt,
			&i.WorkflowRun.DedupKey,
			&i.WorkflowRun.Input,
			&i.WorkflowRun.Dag,
			&i.WorkflowRun.State,
			&i.WorkflowRun.CreatedAt,
			&i.WorkflowRun.FinishedAt,
			&i.JobRun.Id,
			&i.JobRun.JobName,
			&i.JobRun.ScheduleName,
			&i.JobRun.ScheduledAt,
			&i.JobRun.DedupKey,
			&i.JobRun.WorkflowRunId,
			&i.JobRun.ExecutorType,
			&i.JobRun.Params,
			&i.JobRun.Timeout,
			&i.JobRun.RetryPolicy,
			&i.JobRun.State,
			&i.JobRun.Attempt,
			&i.JobRun.CancelRequested,
			&i.JobRun.RunAt,
			&i.JobRun.LeaseExpiresAt,
			&i.JobRun.LeaseToken,
			&i.JobRun.LeaseOwner,
			&i.JobRun.CreatedAt,
			&i.JobRun.StartedAt,
			&i.JobRun.FinishedAt,
			&i.JobRun.Output,
			&i.JobRun.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
